### ISSUE TITLE
24 Build Errors

### ISSUE THREAD

**Issue by Kfeavel** [lufinkey/MobileBrawler#20]
The following files yield build errors upon compile in Xcode 6.3:

**string.mm**
No member named 'total' in 'GameLibrary::String'

**number.cpp:**
Use of overloaded operator '<<' is ambiguous (with operand types 'std::ostream' (aka 'basic_ostream<char>') and 'const char [7]')
